{
 "title": "GreptimeDB-Plugins-Traces",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "info8fcc-greptimedb-datasource" },
   {
    "name": "service",
    "label": "应用名称",
    "query": "SELECT DISTINCT(service_name) FROM opentelemetry_traces_services;"
   },
   {
    "name": "span_name",
    "label": "接口名称",
    "query": "SELECT DISTINCT(span_name) FROM opentelemetry_traces WHERE service_name = '$service'"
   },
   { "name": "status_code", "label": "状态码" }
  ]
 },
 "panels": [
  { "title": "应用列表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "应用列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT \n    t1.service_name AS \"应用名称\",\n    CAST(t1.total_count AS FLOAT) / 60 AS \"每秒请求数\",\n    CONCAT(ROUND(t1.error_count / t1.total_count * 100.0, 2), '%') AS \"错误率\",\n    CONCAT(ROUND(t1.avg_latency_nano / 1000000.0, 2), ' ms') AS \"平均延迟\"\nFROM \n    __otel_traces_services_red_metrics_1m t1\nWHERE \n    t1.time_window_1m = (\n        SELECT MAX(t2.time_window_1m)\n        FROM __otel_traces_services_red_metrics_1m t2\n        WHERE t2.service_name = t1.service_name AND (time_window_1m >= $__fromTime AND time_window_1m <= $__toTime)\n    )\nORDER BY \n    t1.service_name;\n"
    }
   ]
  },
  { "title": "应用概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "请求数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT SUM(total_count) FROM __otel_traces_services_red_metrics_1h WHERE ( time_window_1h >= $__fromTime AND time_window_1h <= $__toTime )  AND service_name = '$service'\n"
    }
   ]
  },
  {
   "title": "错误数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT SUM(error_count) FROM __otel_traces_services_red_metrics_1h WHERE ( time_window_1h >= $__fromTime AND time_window_1h <= $__toTime )  AND service_name = '$service'"
    }
   ]
  },
  {
   "title": "平均延迟",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT ROUND(avg(avg_latency_nano)/1000000.0, 2) FROM __otel_traces_services_red_metrics_1h WHERE ( time_window_1h >= $__fromTime AND time_window_1h <= $__toTime ) AND service_name = '$service'"
    }
   ]
  },
  {
   "title": "请求数/1m",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT total_count,time_window_1m FROM __otel_traces_services_red_metrics_1m WHERE service_name = '$service' AND ( time_window_1m >= $__fromTime AND time_window_1m <= $__toTime ) \n"
    }
   ]
  },
  {
   "title": "错误数/1m",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT error_count,time_window_1m FROM __otel_traces_services_red_metrics_1m WHERE service_name = '$service' AND ( time_window_1m >= $__fromTime AND time_window_1m <= $__toTime ) \n"
    }
   ]
  },
  {
   "title": "延迟/1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT ROUND(avg_latency_nano / 1000000.0, 2) as latency_ms , time_window_1m FROM __otel_traces_services_red_metrics_1m WHERE service_name = '$service' AND ( time_window_1m >= $__fromTime AND time_window_1m <= $__toTime ) \n"
    }
   ]
  },
  {
   "title": "请求数提供服务排行（Top5）",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT\n    span_name,\n    SUM(total_count) AS total_count,\nFROM \n    __otel_traces_spans_red_metrics_1h\nWHERE \n    ( time_window_1h >= $__fromTime AND time_window_1h <= $__toTime )  AND service_name = '$service'\nGROUP BY \n    span_name\nORDER BY \n    SUM(total_count) DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "错误数提供服务排行（Top5）",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT\n    span_name,\n    SUM(error_count) AS error_count,\nFROM \n    __otel_traces_spans_red_metrics_1h\nWHERE \n   ( time_window_1h >= $__fromTime AND time_window_1h <= $__toTime )  AND service_name = '$service'\nGROUP BY \n    span_name\nORDER BY \n    SUM(error_count) DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "平均耗时提供服务排行（Top5）",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT\n    span_name,\n    round(avg(avg_latency_nano) / 1000000.0, 2) AS latency,\nFROM \n    __otel_traces_spans_red_metrics_1h\nWHERE \n    ( time_window_1h >= $__fromTime AND time_window_1h <= $__toTime ) AND service_name = '$service'\nGROUP BY \n    span_name\nORDER BY \n    latency DESC\nLIMIT 5;"
    }
   ]
  },
  { "title": "应用拓扑", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "应用拓扑",
   "type": "nodeGraph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT \n    CONCAT(parent_service, '->', child_service) AS id,\n    parent_service AS source,\n    child_service AS target,\n    call_count AS mainstat,\n    call_count AS value\nFROM \n    __otel_traces_dependencies_1h\n"
    }
   ]
  },
  { "title": "依赖服务", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "依赖服务",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT DISTINCT(child_service) as dependency FROM __otel_traces_dependencies_1h WHERE parent_service = '$service' AND ( time_window_1h >= $__fromTime AND time_window_1h <= $__toTime )\n"
    }
   ]
  },
  { "title": "调用分析", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Span 列表",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT \"trace_id\" as traceID, \"service_name\" as serviceName, \"span_name\" as operationName, \"timestamp\" as startTime, FLOOR(\"duration_nano\" * 0.000001) AS duration FROM \"public\".\"opentelemetry_traces\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) AND ( service_name = '$service' ) ORDER BY timestamp DESC, duration_nano DESC LIMIT 1000"
    }
   ]
  }
 ]
}