{
 "title": "Traces",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "mysql" },
   {
    "name": "service",
    "label": "应用名称",
    "query": "SELECT DISTINCT(service_name) FROM opentelemetry_traces_services;"
   },
   {
    "name": "span_name",
    "label": "接口名称",
    "query": "SELECT DISTINCT(span_name) FROM opentelemetry_traces WHERE service_name = '$service'"
   },
   { "name": "status_code", "label": "状态码" }
  ]
 },
 "panels": [
  {
   "title": "应用概览",
   "type": "table",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT \n  service_name AS \"应用名称\",\n  CAST(COUNT(*) AS FLOAT) / (${__to:date:seconds} - ${__from:date:seconds}) AS \"每秒请求数\",\n  CONCAT(SUM(CASE WHEN `span_attributes.http.status_code` != '200' AND `span_attributes.http.status_code` IS NULL THEN 1 ELSE 0 END) / COUNT(*) * 100.0, '%') AS \"错误率\",\n  CONCAT(ROUND(AVG(duration_nano) / 1000000.0, 2), ' ms') AS \"平均延迟\"\nFROM \n  opentelemetry_traces\nWHERE \n  $__timeFilter(timestamp)\nGROUP BY service_name\nORDER BY service_name;\n"
    }
   ]
  },
  {
   "title": "应用拓扑",
   "type": "nodeGraph",
   "gridPos": { "h": 19, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT \n    CONCAT(parent_service, '->', child_service) AS id,\n    parent_service AS source,\n    child_service AS target,\n    call_count AS mainstat,\n    call_count AS value\nFROM \n    __otel_traces_dependencies_1h\n"
    }
   ]
  },
  {
   "title": "应用接口 RPS",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT span_name, COUNT(*) / 60.0 AS rps, date_bin('60 seconds', timestamp) \n  AS time FROM opentelemetry_traces \nWHERE\n  $__timeFilter(timestamp) AND\n  service_name = '$service'  \nGROUP BY span_name, time, \nORDER BY time"
    }
   ]
  },
  {
   "title": "Span 列表",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT\n  service_name as \"应用名称\",\n  trace_id,\n  span_name as \"接口名称\", \n  CONCAT(duration_nano / 1000000.0, ' ms') AS \"延迟\",\n  IFNULL(`span_attributes.http.status_code`, 'N/A') AS \"状态码\",\n  timestamp as \"开始时间\" FROM opentelemetry_traces \nWHERE service_name = '$service' AND \n$__timeFilter(timestamp) \nAND (\n    \"$span_name\" = \"'all'\"\n    OR span_name in ($span_name)\n)\nAND (\n    \"$status_code\" = \"\"\n    OR `span_attributes.http.status_code` = '$status_code'\n)\nORDER BY timestamp DESC LIMIT 1000;"
    }
   ]
  }
 ]
}