apiVersion: 1

datasources:
  - name: greptimedb-mysql
    type: mysql
    url: greptimedb:4002
    uid: greptimedb-mysql
    jsonData:
      database: public
      sslmode: 'disable'

  - name: greptimedb-jaeger
    type: jaeger
    url: http://greptimedb:4000/v1/jaeger
    uid: greptimedb-jaeger

  - name: greptimedb
    type: info8fcc-greptimedb-datasource
    access: proxy
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    url: http://greptimedb:4000
    jsonData:
      host: http://greptimedb:4000
      database: "public"
      username: ""
